var annotated =
[
    [ "april", null, [
      [ "Gui", null, [
        [ "Dock", "classapril_1_1Gui_1_1Dock.html", "classapril_1_1Gui_1_1Dock" ],
        [ "DockCrtSel_p", "classapril_1_1Gui_1_1DockCrtSel__p.html", "classapril_1_1Gui_1_1DockCrtSel__p" ],
        [ "DockCrtSel", "classapril_1_1Gui_1_1DockCrtSel.html", "classapril_1_1Gui_1_1DockCrtSel" ],
        [ "DockIds_p", "classapril_1_1Gui_1_1DockIds__p.html", "classapril_1_1Gui_1_1DockIds__p" ],
        [ "DockIds", "classapril_1_1Gui_1_1DockIds.html", "classapril_1_1Gui_1_1DockIds" ],
        [ "DockTree_p", "classapril_1_1Gui_1_1DockTree__p.html", "classapril_1_1Gui_1_1DockTree__p" ],
        [ "DockTree", "classapril_1_1Gui_1_1DockTree.html", "classapril_1_1Gui_1_1DockTree" ],
        [ "DockWorld_p", "classapril_1_1Gui_1_1DockWorld__p.html", "classapril_1_1Gui_1_1DockWorld__p" ],
        [ "DockWorld", "classapril_1_1Gui_1_1DockWorld.html", "classapril_1_1Gui_1_1DockWorld" ],
        [ "MW", "classapril_1_1Gui_1_1MW.html", "classapril_1_1Gui_1_1MW" ],
        [ "NewWorldDlg", "classapril_1_1Gui_1_1NewWorldDlg.html", "classapril_1_1Gui_1_1NewWorldDlg" ],
        [ "PlginEntry", "classapril_1_1Gui_1_1PlginEntry.html", "classapril_1_1Gui_1_1PlginEntry" ],
        [ "PluginsDlg", "classapril_1_1Gui_1_1PluginsDlg.html", "classapril_1_1Gui_1_1PluginsDlg" ],
        [ "SceneViewer", "classapril_1_1Gui_1_1SceneViewer.html", "classapril_1_1Gui_1_1SceneViewer" ],
        [ "AGui", "classapril_1_1Gui_1_1AGui.html", "classapril_1_1Gui_1_1AGui" ],
        [ "AGui2D", "classapril_1_1Gui_1_1AGui2D.html", "classapril_1_1Gui_1_1AGui2D" ],
        [ "AGui3D", "classapril_1_1Gui_1_1AGui3D.html", "classapril_1_1Gui_1_1AGui3D" ],
        [ "AQScene", "classapril_1_1Gui_1_1AQScene.html", "classapril_1_1Gui_1_1AQScene" ],
        [ "WorldQScene", "classapril_1_1Gui_1_1WorldQScene.html", "classapril_1_1Gui_1_1WorldQScene" ],
        [ "WqsTAuto", "classapril_1_1Gui_1_1WqsTAuto.html", "classapril_1_1Gui_1_1WqsTAuto" ]
      ] ],
      [ "AaModule", "classapril_1_1AaModule.html", "classapril_1_1AaModule" ],
      [ "AaOutput", "classapril_1_1AaOutput.html", "classapril_1_1AaOutput" ],
      [ "AaToken", "structapril_1_1AaToken.html", "structapril_1_1AaToken" ],
      [ "AaTkString", "structapril_1_1AaTkString.html", "structapril_1_1AaTkString" ],
      [ "AaTokenizer", "classapril_1_1AaTokenizer.html", "classapril_1_1AaTokenizer" ],
      [ "AbstractApril", "classapril_1_1AbstractApril.html", "classapril_1_1AbstractApril" ],
      [ "CommandMap", "classapril_1_1CommandMap.html", "classapril_1_1CommandMap" ],
      [ "AaWorld", "classapril_1_1AaWorld.html", "classapril_1_1AaWorld" ],
      [ "AprilLibrary", "classapril_1_1AprilLibrary.html", "classapril_1_1AprilLibrary" ],
      [ "Actor", "classapril_1_1Actor.html", "classapril_1_1Actor" ],
      [ "ActorComp", "classapril_1_1ActorComp.html", "classapril_1_1ActorComp" ],
      [ "ActorFactory", "classapril_1_1ActorFactory.html", "classapril_1_1ActorFactory" ],
      [ "Actuator", "classapril_1_1Actuator.html", "classapril_1_1Actuator" ],
      [ "ActuatorFactory", "classapril_1_1ActuatorFactory.html", "classapril_1_1ActuatorFactory" ],
      [ "Brain", "classapril_1_1Brain.html", "classapril_1_1Brain" ],
      [ "BrainFactory", "classapril_1_1BrainFactory.html", "classapril_1_1BrainFactory" ],
      [ "Component", "classapril_1_1Component.html", "classapril_1_1Component" ],
      [ "Director", "classapril_1_1Director.html", "classapril_1_1Director" ],
      [ "DNA", "classapril_1_1DNA.html", "classapril_1_1DNA" ],
      [ "DNAView", "classapril_1_1DNAView.html", "classapril_1_1DNAView" ],
      [ "EventData", "classapril_1_1EventData.html", "classapril_1_1EventData" ],
      [ "EventFactory", "classapril_1_1EventFactory.html", "classapril_1_1EventFactory" ],
      [ "EventLine", "classapril_1_1EventLine.html", "classapril_1_1EventLine" ],
      [ "EventSource", "classapril_1_1EventSource.html", "classapril_1_1EventSource" ],
      [ "Factory", "classapril_1_1Factory.html", "classapril_1_1Factory" ],
      [ "Reflex", "classapril_1_1Reflex.html", "classapril_1_1Reflex" ],
      [ "ReflexFactory", "classapril_1_1ReflexFactory.html", "classapril_1_1ReflexFactory" ],
      [ "Sensor", "classapril_1_1Sensor.html", "classapril_1_1Sensor" ],
      [ "SensorFactory", "classapril_1_1SensorFactory.html", "classapril_1_1SensorFactory" ],
      [ "UniqueId", "classapril_1_1UniqueId.html", "classapril_1_1UniqueId" ],
      [ "World", "classapril_1_1World.html", "classapril_1_1World" ],
      [ "WorldFactory", "classapril_1_1WorldFactory.html", "classapril_1_1WorldFactory" ]
    ] ],
    [ "ABOX2D", "structABOX2D.html", "structABOX2D" ],
    [ "ABOX3D", "structABOX3D.html", "structABOX3D" ],
    [ "AprilPluginInterf", "classAprilPluginInterf.html", "classAprilPluginInterf" ],
    [ "AprilPluginLoader", "classAprilPluginLoader.html", "classAprilPluginLoader" ],
    [ "P2D", "structP2D.html", "structP2D" ],
    [ "P3D", "structP3D.html", "structP3D" ],
    [ "WQS_Unit", "classWQS__Unit.html", "classWQS__Unit" ]
];